# Generated by Django 3.1.5 on 2021-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210104_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='expense_name',
            field=models.TextField(default='Test'),
        ),
    ]
