# Generated by Django 3.1.5 on 2021-01-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expenseinfo_expense_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_budget', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='date_added',
            field=models.DateField(default='1960-01-01'),
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_budget', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accountinfo')),
            ],
        ),
    ]
